export const basicList = [
    "Open to-do list",
    "Make a bed",
    "Brush teeth",
    "Wordle",
    "Stretch, push-ups",
    "Cold shower",
    "Glass of water",
    "Brush hair",
    "Breakfast",
    "Leetcode challenge",
    "Work smart, not hard",
    "Check exchange rates",
    "Finance management",
    "Eat a fruit",
    "Talk to a friend",
    "Tasty lunch",
    "Take a selfie",
    "Cardio 8'000 steps",
    "Check email & reply",
    "Read an article, book",
    "Relax and rest",
    "Podcast",
    "Dinner",
    "Wash dishes",
    "Brush teeth before bed",
    "23:00 - go to sleep",
];
export const storage_key = "SIA_TASKS_STATE";
export const total_percent = 100;